version: '3'
services:
  app:
    # image: mahilkuvadiya/ai-quizzer-3
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - mynetwork

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge